name = "jiwonz/darklua_lune"
version = "0.1.4"
description = "darklua + lune scriptable CLI interface"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/darklua-lune"
license = "MIT"
includes = ["LICENSE", "pesde.toml", "README.md", "src/**"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.9.4"
pesde = "^0.7.0-rc.1"

[dependencies]
dirs = { name = "jiwonz/dirs", version = "^0.5.1" }
greentea = { name = "corecii/greentea", version = "^0.4.11" }
