name = "jiwonz/darklua_lune"
version = "0.1.0"
description = "darklua + lune scriptable CLI interface"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/darklua-lune"
license = "MIT"
includes = ["LICENSE", "pesde.toml", "README.md", "src/**"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
typegen = "scripts/typegen.luau"

[dev_dependencies]
selene = { name = "pesde/selene", version = "^0.28.0" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.38.0" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }

[peer_dependencies]
darklua = { name = "pesde/darklua", version = "^0.16.0" }

[dependencies]
dirs = { name = "jiwonz/dirs", version = "^0.3.0" }
greentea = { name = "corecii/greentea", version = "^0.4.11" }
