name = "jiwonz/darklua_lune"
version = "0.1.2"
description = "darklua + lune scriptable CLI interface"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/darklua-lune"
license = "MIT"
includes = ["LICENSE", "pesde.toml", "README.md", "src/**"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
typegen = "scripts/typegen.luau"

[peer_dependencies]
darklua = { name = "pesde/darklua", version = "^0.16.0" }

[dependencies]
dirs = { name = "jiwonz/dirs", version = "^0.3.0" }
greentea = { name = "corecii/greentea", version = "^0.4.11" }
pesde_exec = { name = "jiwonz/pesde_exec", version = "^0.3.3" }

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.5" }
